import { designConfig } from '@/config/design.config';

export const colors = {
  light: {
    background: '#FFFFFF',
    foreground: '#212121',
    card: '#FFFFFF',
    'card-foreground': '#212121',
    popover: '#FFFFFF',
    'popover-foreground': '#212121',
    primary: designConfig.colors.primary.main,
    'primary-foreground': designConfig.colors.primary.contrast,
    secondary: designConfig.colors.secondary.main,
    'secondary-foreground': designConfig.colors.secondary.contrast,
    muted: designConfig.colors.background.paper,
    'muted-foreground': designConfig.colors.text.secondary,
    accent: designConfig.colors.accent.main,
    'accent-foreground': designConfig.colors.accent.contrast,
    destructive: designConfig.colors.error.main,
    'destructive-foreground': '#FFFFFF',
    border: '#E0E0E0',
    input: '#E0E0E0',
    ring: designConfig.colors.primary.main,
  },
  dark: {
    background: '#121212',
    foreground: '#FFFFFF',
    card: '#1E1E1E',
    'card-foreground': '#FFFFFF',
    popover: '#1E1E1E',
    'popover-foreground': '#FFFFFF',
    primary: designConfig.colors.primary.light,
    'primary-foreground': '#FFFFFF',
    secondary: designConfig.colors.secondary.light,
    'secondary-foreground': '#212121',
    muted: '#2E2E2E',
    'muted-foreground': '#BDBDBD',
    accent: designConfig.colors.accent.light,
    'accent-foreground': '#FFFFFF',
    destructive: designConfig.colors.error.light,
    'destructive-foreground': '#FFFFFF',
    border: '#404040',
    input: '#404040',
    ring: designConfig.colors.primary.light,
  },
};

